# Generated by Django 3.2.7 on 2021-09-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='wallet_name',
            new_name='wallet',
        ),
    ]
