# Generated by Django 3.2.7 on 2021-09-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_wallet_name_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('E', 'Expense'), ('I', 'Income')], default='E', max_length=10),
        ),
    ]
